import ThemeSelector from '@/components/ThemeSelector'
import { Toaster } from '@/components/ui/Sonner'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const themeScript = `
const preferTheme = localStorage.getItem("theme") || 'system'
const systemTheme = window.matchMedia("(prefers-color-scheme: dark)").matches
  ? "dark"
  : "light";


if (preferTheme === 'system') {
  document.documentElement.classList.add(systemTheme);
} else {
  document.documentElement.classList.add(preferTheme);
}

if (!localStorage.getItem("theme")) {
  localStorage.setItem("theme", "system");
}
`

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh-TW" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased`}
      >
        {children}
        <Toaster />
        <ThemeSelector />
      </body>
    </html>
  )
}
